"""Write hierarchical KiCad schematics for every board in design.py.

Layout strategy (deliberately mechanical, readable, and ERC-clean): each block is a
sub-sheet; every symbol is placed on a grid; every connected pin gets a short wire
stub ending in a global label named after its net; unconnected pins get a no-connect
flag.  Nets that have power-input pins but no power-output driver get a PWR_FLAG.
"""
import math, os, sys, uuid, datetime
from sexp import dump, find, find1, Sym as S
from kilib import get_symbol, pins as sym_pins, prop as sym_prop
import design

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LOCAL_LIBS = [os.path.join(ROOT, "lib")]
G = 2.54
SCH_VERSION = 20250114
TODAY = os.environ.get("PNEUMA_REV_DATE", design.REV_DATE)


def U(*seed):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "pneuma/" + "/".join(map(str, seed))))


def snap(v):
    return round(round(v / 1.27) * 1.27, 4)


def font(size=1.27):
    return [S("font"), [S("size"), size, size]]


def eff(hide=False, justify=None, size=1.27):
    e = [S("effects"), font(size)]
    if justify:
        e.append([S("justify")] + [S(j) for j in justify.split()])
    if hide:
        e.append([S("hide"), S("yes")])
    return e


def title_block(board, sheet_title, comment=""):
    return [S("title_block"), [S("title"), sheet_title], [S("date"), TODAY], [S("rev"), "A"],
            [S("company"), "Pneuma"], [S("comment"), 1, board.title],
            [S("comment"), 2, "Generated by hardware/kicad/tools/gen_sch.py from design.py - edit the source, not this file"],
            [S("comment"), 3, comment]]


def lib_symbol(lib_id):
    s = get_symbol(lib_id, LOCAL_LIBS)
    return s


class Sheet:
    def __init__(self, board, name, idx, root_uuid):
        self.board, self.name, self.idx = board, name, idx
        self.uuid = U(board.name, "sheet", name)
        self.file = name.lower() + ".kicad_sch"
        self.root_uuid = root_uuid
        self.items, self.libs = [], {}

    def path(self):
        return f"/{self.root_uuid}/{self.uuid}"


def place_symbol(sheet, part, x, y, pinmap):
    lib_id = part["lib_id"]
    sd = sheet.libs.setdefault(lib_id, lib_symbol(lib_id))
    ref, board = part["ref"], sheet.board
    sym_uuid = U(board.name, "sym", ref)
    props = [[S("property"), "Reference", ref, [S("at"), x, y - 1.27, 0], eff(justify="left")],
             [S("property"), "Value", part["value"], [S("at"), x, y + 1.27, 0], eff(justify="left")],
             [S("property"), "Footprint", part["footprint"], [S("at"), x, y, 0], eff(hide=True)],
             [S("property"), "Datasheet", sym_prop(sd, "Datasheet") or "", [S("at"), x, y, 0], eff(hide=True)]]
    for k, v in part["fields"].items():
        props.append([S("property"), k, str(v), [S("at"), x, y, 0], eff(hide=True)])
    pins = sym_pins(sd)
    inst = [S("symbol"), [S("lib_id"), lib_id], [S("at"), x, y, 0], [S("unit"), 1],
            [S("exclude_from_sim"), S("no")], [S("in_bom"), S("yes")], [S("on_board"), S("yes")],
            [S("dnp"), S("yes") if part["dnp"] else S("no")], [S("uuid"), sym_uuid]] + props
    for p in pins:
        inst.append([S("pin"), p[0], [S("uuid"), U(board.name, ref, "pin", p[0])]])
    inst.append([S("instances"), [S("project"), board.name,
                                  [S("path"), sheet.path(), [S("reference"), ref], [S("unit"), 1]]]])
    sheet.items.append(inst)
    return sym_uuid


def stub_and_label(sheet, key, x, y, ang, net, nc):
    """Pin end at (x,y) sch coords; ang = lib pin angle (direction toward body)."""
    out_ang = (ang + 180) % 360
    dx, dy = round(math.cos(math.radians(out_ang))), -round(math.sin(math.radians(out_ang)))
    if nc:
        sheet.items.append([S("no_connect"), [S("at"), x, y], [S("uuid"), U(key, "nc")]])
        return
    x2, y2 = snap(x + dx * G), snap(y + dy * G)
    sheet.items.append([S("wire"), [S("pts"), [S("xy"), x, y], [S("xy"), x2, y2]],
                        [S("stroke"), [S("width"), 0], [S("type"), S("default")]], [S("uuid"), U(key, "w")]])
    lab_ang = {(1, 0): 0, (-1, 0): 180, (0, -1): 90, (0, 1): 270}[(dx, dy)]
    just = "left" if lab_ang in (0, 90) else "right"
    sheet.items.append([S("global_label"), net, [S("shape"), S("passive")], [S("at"), x2, y2, lab_ang],
                        [S("fields_autoplaced"), S("yes")], eff(justify=just), [S("uuid"), U(key, "gl")],
                        [S("property"), "Intersheetrefs", "${INTERSHEET_REFS}", [S("at"), x2, y2, 0], eff(hide=True)]])


def extents(pins, pinmap):
    """Approximate bbox of a placed symbol incl. stubs and labels, relative to origin (sch coords)."""
    xs, ys = [0.0], [0.0]
    for num, name, px, py, ang, ln, et, u, hid in pins:
        if hid:
            continue
        x, y = px, -py
        net = pinmap.get(num)
        lab = (len(net) * 1.0 + 4.5) if net else 1.5
        oa = (ang + 180) % 360
        dx, dy = round(math.cos(math.radians(oa))), -round(math.sin(math.radians(oa)))
        xs += [x, x + dx * (G + lab)]
        ys += [y, y + dy * (G + lab)]
        # body half-width guess from pin length
        xs += [x - dx * (ln + 4)]
        ys += [y - dy * (ln + 4)]
    return min(xs) - 2, max(xs) + 2, min(ys) - 3.5, max(ys) + 3.5


def build_sheet(sheet, parts, power_nets_needing_flag):
    x_cur, y_cur, row_h = 25.4, 30.48, 0.0
    max_w = 520.0
    # big parts first for a tidier layout
    order = sorted(parts, key=lambda p: -len(p["pins"]))
    for part in order:
        sd = sheet.libs.setdefault(part["lib_id"], lib_symbol(part["lib_id"]))
        pins = sym_pins(sd)
        pinmap = {k: v for k, v in part["pins"].items()}
        x0, x1, y0, y1 = extents(pins, pinmap)
        w, h = x1 - x0, y1 - y0
        if x_cur + w > max_w:
            x_cur, y_cur, row_h = 25.4, y_cur + row_h + 5.08, 0.0
        ox, oy = snap(x_cur - x0), snap(y_cur - y0)
        place_symbol(sheet, part, ox, oy, pinmap)
        seen = {}
        for num, name, px, py, ang, ln, et, u, hid in pins:
            if hid:
                continue
            ex, ey = snap(ox + px), snap(oy - py)
            net = pinmap.get(num)
            if (ex, ey) in seen:          # stacked pins must share a net
                assert seen[(ex, ey)] == net, (part["ref"], num, net, seen[(ex, ey)])
                continue
            seen[(ex, ey)] = net
            nc = (not net) or et == "no_connect"
            stub_and_label(sheet, f"{sheet.board.name}/{part['ref']}/{num}", ex, ey, ang, net, nc)
        x_cur += w + 5.08
        row_h = max(row_h, h)
    # PWR_FLAGs for this sheet's share of power nets
    for i, net in enumerate(power_nets_needing_flag):
        fx, fy = snap(25.4 + (i % 8) * 30.48), snap(y_cur + row_h + 15.24 + (i // 8) * 15.24)
        part = dict(ref=f"#FLG{sheet.idx}{i:02d}", lib_id="power:PWR_FLAG", value="PWR_FLAG", footprint="",
                    pins={"1": net}, dnp=False, fields={})
        sd = sheet.libs.setdefault("power:PWR_FLAG", lib_symbol("power:PWR_FLAG"))
        place_symbol(sheet, part, fx, fy, part["pins"])
        for num, name, px, py, ang, ln, et, u, hid in sym_pins(sd):
            stub_and_label(sheet, f"{sheet.board.name}/flag/{net}", snap(fx + px), snap(fy - py), ang, net, False)
    return y_cur + row_h


def sheet_file(sheet, board, paper="A1"):
    libs = [S("lib_symbols")] + list(sheet.libs.values())
    doc = [S("kicad_sch"), [S("version"), SCH_VERSION], [S("generator"), "eeschema"], [S("generator_version"), "9.0"],
           [S("uuid"), U(board.name, "file", sheet.name)], [S("paper"), paper],
           title_block(board, f"{board.title} - {sheet.name}"), libs] + sheet.items + [[S("embedded_fonts"), S("no")]]
    return dump(doc) + "\n"


def power_flag_nets(board):
    drivers, sinks = set(), set()
    for part in board.parts:
        pins = {p[0]: p[6] for p in sym_pins(lib_symbol(part["lib_id"]))}
        for num, net in part["pins"].items():
            if not net:
                continue
            et = pins.get(num)
            if et == "power_out":
                drivers.add(net)
            if et == "power_in":
                sinks.add(net)
    return sorted(sinks - drivers)


def write_board(board):
    outdir = os.path.join(ROOT, board.name)
    os.makedirs(outdir, exist_ok=True)
    root_uuid = U(board.name, "root")
    flags = power_flag_nets(board)
    parts_by_ref = {p["ref"]: p for p in board.parts}
    sheets = []
    for i, (name, refs) in enumerate(board.sheets):
        sh = Sheet(board, name, i + 2, root_uuid)
        build_sheet(sh, [parts_by_ref[r] for r in refs], flags if i == 0 else [])
        open(os.path.join(outdir, sh.file), "w").write(sheet_file(sh, board))
        sheets.append(sh)
    # root sheet: sheet symbols + notes
    items = []
    for i, sh in enumerate(sheets):
        x, y, w, h = 30.48 + (i % 3) * 76.2, 45.72 + (i // 3) * 50.8, 60.96, 30.48
        items.append([S("sheet"), [S("at"), x, y], [S("size"), w, h], [S("exclude_from_sim"), S("no")],
                      [S("in_bom"), S("yes")], [S("on_board"), S("yes")], [S("dnp"), S("no")],
                      [S("fields_autoplaced"), S("yes")],
                      [S("stroke"), [S("width"), 0.1524], [S("type"), S("solid")]],
                      [S("fill"), [S("color"), 0, 0, 0, 0.0]], [S("uuid"), sh.uuid],
                      [S("property"), "Sheetname", sh.name, [S("at"), x, y - 0.7112, 0], eff(justify="left bottom")],
                      [S("property"), "Sheetfile", sh.file, [S("at"), x, y + h + 0.5846, 0], eff(justify="left top")],
                      [S("instances"), [S("project"), board.name, [S("path"), f"/{root_uuid}", [S("page"), str(i + 2)]]]]])
    notes = NOTES.get(board.name, [])
    for j, line in enumerate(notes):
        items.append([S("text"), line, [S("exclude_from_sim"), S("no")], [S("at"), 30.48, 160 + j * 4.5, 0],
                      eff(justify="left"), [S("uuid"), U(board.name, "note", j)]])
    doc = [S("kicad_sch"), [S("version"), SCH_VERSION], [S("generator"), "eeschema"], [S("generator_version"), "9.0"],
           [S("uuid"), root_uuid], [S("paper"), "A3"], title_block(board, board.title), [S("lib_symbols")]] + items + [
        [S("sheet_instances"), [S("path"), "/", [S("page"), "1"]]], [S("embedded_fonts"), S("no")]]
    open(os.path.join(outdir, board.name + ".kicad_sch"), "w").write(dump(doc) + "\n")
    write_tables(outdir, board)
    return outdir, root_uuid, sheets


def write_tables(outdir, board=None):
    """Project-local tables: Pneuma libs + the stock KiCad libs this board uses (via KiCad path vars)."""
    syms, fps = {"Pneuma"}, {"Pneuma"}
    if board:
        for p in board.parts:
            syms.add(p["lib_id"].split(":")[0])
            if p["footprint"]:
                fps.add(p["footprint"].split(":")[0])
        syms.add("power")
    sl = ['(sym_lib_table', '  (version 7)']
    for n in sorted(syms):
        uri = "${KIPRJMOD}/../lib/Pneuma.kicad_sym" if n == "Pneuma" else "${KICAD10_SYMBOL_DIR}/" + n + ".kicad_sym"
        sl.append(f'  (lib (name "{n}")(type "KiCad")(uri "{uri}")(options "")(descr ""))')
    fl = ['(fp_lib_table', '  (version 7)']
    for n in sorted(fps):
        uri = "${KIPRJMOD}/../lib/Pneuma.pretty" if n == "Pneuma" else "${KICAD10_FOOTPRINT_DIR}/" + n + ".pretty"
        fl.append(f'  (lib (name "{n}")(type "KiCad")(uri "{uri}")(options "")(descr ""))')
    open(os.path.join(outdir, "sym-lib-table"), "w").write("\n".join(sl + [")"]) + "\n")
    open(os.path.join(outdir, "fp-lib-table"), "w").write("\n".join(fl + [")"]) + "\n")


NOTES = {
    "pneuma-main": [
        "PNM-MAIN Rev A notes",
        "1. U3 (MDBT50Q) runs in nRF52840 high-voltage mode: VDDH = VSYS, VDD is an OUTPUT (+3V3_AON, <=25 mA).",
        "   Firmware must program UICR.REGOUT0 = 3.3 V on first boot (factory default is 1.8 V). P0.18 must be PSELRESET.",
        "2. Core1106 pins 60/61/62/67 (WiFi control via 1k) and 63/64/68/69 (BT UART) are shared on the -1408 variant: do not use.",
        "3. nRF must drive SoC-facing lines (SOC_RX, SOC_WAKE, SOC_NPOR) low or Hi-Z whenever SOC_EN is low (no back-powering).",
        "4. Camera J4 follows the Luckfox 20P pinout. Verify FFC contact side / pin-1 with the SC3336 (B) before ordering the compact module.",
        "5. J5 -> PNM-PWR J5 over a straight-through 30P 0.5 mm FFC routed under the battery.",
    ],
    "pneuma-pwr": [
        "PNM-PWR Rev A notes",
        "1. BQ24074 OUT (VSYS) regulates to 4.4 V > EG800Q VBAT max 4.3 V, so the modem is on VBAT (battery node), per Quectel practice.",
        "   Modem load on VBAT can prevent charge termination while USB is present: firmware keeps the modem in DRX/sleep when charging.",
        "2. U4 routes the SoC USB to USB-C (USB_SEL=0, default: flashing/ADB) or to the modem (USB_SEL=1). R13 asserts modem USB_VBUS with SEL.",
        "3. U6 VCCB = +3V3_SOC so the modem-UART translator is fully off when the SoC is unpowered.",
        "4. RF pi-match R14/C13/C14 must be tuned on the final antenna; U.FL J3 is the bench antenna feed.",
    ],
}


if __name__ == "__main__":
    for mk in design.BOARDS:
        b = mk()
        out, root, sheets = write_board(b)
        print("wrote", out, [s.file for s in sheets])
